### ISSUE TITLE
Object being shown in apprise format

### ISSUE THREAD

**Issue by luismanson** [geluk/matrix-webhook-gateway#59]
Hello, im looking at the features of different webhook formats and noticed that using apprise with any valid "type" in the request the bot prints [Object object] in the first line of the message

**Comment by wfdewith** [comment]
Thanks for the report. This was indeed a bug in the formatting code. I've proposed a fix in #60.

**Comment by luismanson** [comment]
Thanks for the fix! i'll merge them on my branch and test. Sorry I did not create a PR on my fork, I have no coding experience.

**Comment by geluk** [comment]
No worries! I lost track of this issue, otherwise I would have picked it up earlier.

I'll publish a new release soon, which will also include this fix.
